version: "3"

services:
  portal:
    container_name: django-fac-exmaple
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: realdecoy/django-fac-exmaple
    volumes:
      - ../:/app/
    ports:
      - "8000:8000"

